### ISSUE TITLE
Integration stopped working

### ISSUE THREAD

**Issue by nightfever77** [yo-han/Home-Assistant-Carelink#36] opened 2023-06-27 19:52 UTC
Today the integration stopped working and wanted a re-setup. 
But my credentials won't be accepted anymore. Authentication within Minimed app and on carelink.minimed.com is still working.
Maybe Medtronic changed something with anthentication ?

**Comment by yo-han** [comment] 2023-06-27 20:00
Carelink had maintenance today and after they send out an email to notify their clients the service is down. Right now nobody can login. It's best to wait for Carelink to come up again I guess.

**Comment by nightfever77** [comment] 2023-06-27 20:02
Haha, thanks for the info. I got that email today but just flew over it.
Sorry for bothering.

**Comment by nightfever77** [comment] 2023-06-28 07:05
Got an email, that Medtronic fixed the software issue. But I am still getting the invalid credentials error only with the integration.

**Comment by Mister86NL** [comment] 2023-06-28 07:48
Yeap, same here:

Logger: custom_components.carelink
Source: custom_components/carelink/api.py:435 
Integration: carelink 
First occurred: 00:12:56 (433 occurrences) 
Last logged: 09:43:59

Unexpected error fetching carelink data: 'auth_tmp_token'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/carelink/__init__.py", line 149, in _async_update_data
    recent_data = await self.client.get_recent_data()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/carelink/api.py", line 473, in get_recent_data
    if await self.__get_authorization_token() is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/carelink/api.py", line 435, in __get_authorization_token
    auth_token = self.async_client.cookies[CARELINK_AUTH_TOKEN_COOKIE_NAME]
                 ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 1148, in __getitem__
    raise KeyError(name)
KeyError: 'auth_tmp_token'

**Comment by hhuitema** [comment] 2023-06-28 08:11
My carelink account (which i also use in the regular app) got completely reset. I have to re-allow the carelink user to request access from the patient to monitor. During the outage something weird happened, so for now my account does not have access.
I also had to reconfirm terms and conditions when using the app.

So all these things might affect access using the Integration. If it works in the app, the integration should also work.

**Comment by nightfever77** [comment] 2023-06-28 08:20
I re-authenticated the app and re-confirmed terms and conditions yesterday night.
The app is now connected with my carelink account and synchronizes well as before. It's only the integration which can not connect.

**Comment by yo-han** [comment] 2023-06-28 09:01
Just merged a PR from @sedy89 that should fix the auth issue caused by the medtronic update. https://github.com/yo-han/Home-Assistant-Carelink/pull/37

I will create a new release in a few minutes.

**Comment by hhuitema** [comment] 2023-06-28 09:03
I just checked with a second account and indeed i see also the session errors. This is by the way similar to the Python CLI client which is the foundation of this integration.

Something has definitely changed on the medtronic side.

**Comment by nightfever77** [comment] 2023-06-28 09:22
Updated to 2023.6.5. --> Working. 
Thank you for the quick fix.

**Closed as completed** 2023-06-28 10:17 UTC

**Comment by hhuitema** [comment] 2023-06-28 14:35
For me with 2023.6.5 and the develop branch i am not able to login, using an app working carelink account.
I de-installed the customer component completely and reconfigured from scratch. in all versions i am getting wrong username / password. :-(

**Comment by Mister86NL** [comment] 2023-06-28 14:38
@hhuitema Yeap, me too. App on phone works fine, integration in HA only complains for wrong username/pw.
