### ISSUE TITLE
Most values don't update

### ISSUE THREAD

**Issue by timvermeulen** [yo-han/Home-Assistant-Carelink#15] opened 2023-02-06 04:11 UTC
Thanks for making this integration!

I've installed the integration and I'm able to authenticate and see my values just fine. The problem I'm having is that nearly all values aren't updated continuously, unless I reload the integration manually. The only entities that do get continuous updates are `sensor.last_glucose_level_mmol` and `sensor.last_glucose_level_mg_dl`. All the other ones are just stuck on the value at the time the integration was last reloaded.

I've looked at the logs, and the `DEBUG (MainThread) [custom_components.carelink] _async_update_data:` logs contain accurate, up to date information. So the `_async_update_data` function seems to be working fine. But for one reason or another, only those two keys are then propagated properly into my Home Assistent on each poll.

Any idea what could be causing this?

**Comment by hhuitema** [comment] 2023-02-06 14:25
When i upgraded this morning to the latest release of homeassistant i have exactly the same problem. Before this update of HA all was running fine.

**Comment by yo-han** [comment] 2023-02-06 14:53
It's a problem on my end. Just checked and saw the same as @hhuitema after the update. It looks like the sensors do not have the correct `state class`. I'll keep you posted about a fix.

**Comment by yo-han** [comment] 2023-02-06 17:09
Pushed a fix. I hope this helps you too.

**Comment by timvermeulen** [comment] 2023-02-06 21:39
I don't think this has fixed it for me, I'm seeing the same behavior as before. 😕

**Comment by yo-han** [comment] 2023-02-06 22:31
Hmm, I see it now too. Found some new issues in the logs. I'll make a quick fix for now and will take a longer look later.

**Comment by timvermeulen** [comment] 2023-02-06 23:20
I just updated to 2023.2.2, and it seems to work perfectly now! Thanks a lot for the quick fix 🙂

**Comment by yo-han** [comment] 2023-02-07 21:12
Nice. Good to hear. Is yours working a again too @hhuitema? If so I close this issue.

**Comment by hhuitema** [comment] 2023-02-08 09:16
Hi all, I can confirm that it works as before for me also. :)

Thanks for the quick fix.

**Closed as completed** 2023-02-08 20:56 UTC
